version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: fastapi

  beehive:
    image: beehive3
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /etc/jinniu
    env_file: .env
